# Generated by Django 5.1.2 on 2025-02-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_alter_categoria_img_1_alter_project_img_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='img_10',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_11',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_12',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_13',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_14',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_15',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_16',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_6',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_7',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_8',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_9',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
