# Generated by Django 5.1.2 on 2025-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_remove_project_img_10_remove_project_img_11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='img_10',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='img_6',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='img_7',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='img_8',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='img_9',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
