# Generated by Django 5.1.2 on 2025-02-20 01:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_alter_categoria_img_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
